#!/bin/bash

LAMBDA=1.0
python run_hw3.py env_name=Hopper-v2 \
                  ep_len=1000 \
                  rl_alg=reinforce \
                  estimate_advantage_args.discount=0.99 \
                  n_iter=300 \
                  computation_graph_args.n_layers=2 \
                  computation_graph_args.size=32 \
                  batch_size=2000 \
                  computation_graph_args.learning_rate=0.001 \
                  estimate_advantage_args.reward_to_go=true \
                  estimate_advantage_args.nn_baseline=true \
                  estimate_advantage_args.gae_lambda=${LAMBDA} \
                  exp_name=q5_b2000_r0.001_lambda${LAMBDA} \
                  no_gpu=true

LAMBDA=0.99
python run_hw3.py env_name=Hopper-v2 \
                  ep_len=1000 \
                  rl_alg=reinforce \
                  estimate_advantage_args.discount=0.99 \
                  n_iter=300 \
                  computation_graph_args.n_layers=2 \
                  computation_graph_args.size=32 \
                  batch_size=2000 \
                  computation_graph_args.learning_rate=0.001 \
                  estimate_advantage_args.reward_to_go=true \
                  estimate_advantage_args.nn_baseline=true \
                  estimate_advantage_args.gae_lambda=${LAMBDA} \
                  exp_name=q5_b2000_r0.001_lambda${LAMBDA} \
                  no_gpu=true
LAMBDA=0.95
python run_hw3.py env_name=Hopper-v2 \
                  ep_len=1000 \
                  rl_alg=reinforce \
                  estimate_advantage_args.discount=0.99 \
                  n_iter=300 \
                  computation_graph_args.n_layers=2 \
                  computation_graph_args.size=32 \
                  batch_size=2000 \
                  computation_graph_args.learning_rate=0.001 \
                  estimate_advantage_args.reward_to_go=true \
                  estimate_advantage_args.nn_baseline=true \
                  estimate_advantage_args.gae_lambda=${LAMBDA} \
                  exp_name=q5_b2000_r0.001_lambda${LAMBDA} \
                  no_gpu=true
LAMBDA=0.0
python run_hw3.py env_name=Hopper-v2 \
                  ep_len=1000 \
                  rl_alg=reinforce \
                  estimate_advantage_args.discount=0.99 \
                  n_iter=300 \
                  computation_graph_args.n_layers=2 \
                  computation_graph_args.size=32 \
                  batch_size=2000 \
                  computation_graph_args.learning_rate=0.001 \
                  estimate_advantage_args.reward_to_go=true \
                  estimate_advantage_args.nn_baseline=true \
                  estimate_advantage_args.gae_lambda=${LAMBDA} \
                  exp_name=q5_b2000_r0.001_lambda${LAMBDA} \
                  no_gpu=true
